// packages/client/src/components/Terminal.svelte
<script lang="ts">
  import Typewriter from "$components/Typewriter.svelte";
  import {
    addTerminalContent,
    currentContentItem,
    nextItem,
    terminalContent,
  } from "$lib/stores/terminal_store";
  import { transferToken } from "$lib/tokens/interaction";
  import { onMount, tick } from "svelte";
  import { commandHandler } from "../lib/terminalCommands/commandHandler";
  import { get } from "svelte/store";
  import { Dojo_Status } from "$lib/stores/dojo_store";
  import TerminalLine from "./TerminalLine.svelte";

  let inputValue = "";
  let originalInputValue = "";
  let inputHistory: string[] = [];
  let inputHistoryIndex = 0;
  let terminalForm: HTMLFormElement;
  let terminalInput: HTMLInputElement;

  // State to track if we're waiting for user input for the RecipientAddress, token Id
  let waitingForRecipientAddress = false;
  let waitingForTokenId = false;
  let recipientAddress = "";
  let token_ID: number | null = null;

  function handleKeyDown(e: KeyboardEvent) {
    // up down cycle through prevInputs or back to originalInputValue
    switch (e.key) {
      case "ArrowUp":
        e.preventDefault();
        if (inputHistoryIndex === 0) {
          originalInputValue = inputValue;
        }
        if (inputHistoryIndex < inputHistory.length) {
          inputHistoryIndex++;
          inputValue = inputHistory[inputHistory.length - inputHistoryIndex];
        }
        break;
      case "ArrowDown":
        e.preventDefault();
        if (inputHistoryIndex > 0) {
          inputHistoryIndex--;
          if (inputHistoryIndex === 0) {
            inputValue = originalInputValue;
          } else {
            inputValue = inputHistory[inputHistory.length - inputHistoryIndex];
          }
        }
        break;
      case "Escape":
        e.preventDefault();
        nextItem(get(currentContentItem));
        break;
      default:
        break;
    }
  }

  onMount(() => {
    if (terminalInput) {
      terminalInput.focus();
    }
    setTimeout(() => {
      if (get(Dojo_Status).status !== "spawning") {
        Dojo_Status.set({
          status: "error",
          error: "TIMEOUT",
        });
      }
    }, 5000);
  });

  Dojo_Status.subscribe((status) => {
    console.log(status);
    if (status.status === "spawning") return;
    if (status.status === "initialized") {
      addTerminalContent({
        text: [
          "\n",
          "The O'Ruggin Trail, no:23",
          "from the good folk at",
          "\n",
          "Archetypal Tech ✯",
          "\n\n\n\n\n\n\n\n\n\n",
        ].join("\n"),
        format: "system",
        useTypewriter: true,
        speed: 4,
        style: "text-align: center",
      });
      addTerminalContent({
        text: 'type [command] [target], or type "help"',
        format: "input",
        useTypewriter: true,
      });
      Dojo_Status.set({
        status: "spawning",
        error: null,
      });
      return;
    }
    if (status.status === "error") {
      addTerminalContent({
        text: `FATAL+ERROR: ${status.error}`,
        format: "error",
        useTypewriter: false,
      });
      // TODO: if we have this error we can do an interval check to ping the backend, in case it responds we reload the page
      return;
    }
  });

  async function submitForm(e: SubmitEvent) {
    e.preventDefault();
    const command = inputValue;
    inputHistoryIndex = 0;
    if (command === "") return;
    inputValue = "";
    await tick();
    // Add command to history and display
    inputHistory = [...inputHistory, command];
    commandHandler(command);
  }

  // Handle the Recipient Address introduced
  async function handleRecipientAddressInput(e: SubmitEvent) {
    e.preventDefault();
    const address = inputValue.trim();

    if (!address) {
      addTerminalContent({
        text: "Invalid address. Please provide a valid account address.",
        format: "error",
        useTypewriter: true,
      });
      return;
    }

    recipientAddress = address;
    waitingForRecipientAddress = false;

    // Now ask for the token ID
    addTerminalContent({
      text: "Please provide the token ID of the Ferry Ticket you want to transfer.",
      format: "shog",
      useTypewriter: true,
    });

    waitingForTokenId = true; // Enable token ID input state
    inputValue = "";
    await tick();
  }

  // Handle the Ferry Ticket ID
  async function handleTokenIdInput(e: SubmitEvent) {
    e.preventDefault();
    const tokenIdInput = inputValue.trim();

    if (!tokenIdInput || Number.isNaN(Number(tokenIdInput))) {
      addTerminalContent({
        text: "Invalid token ID. Please provide a valid number.",
        format: "error",
        useTypewriter: true,
      });
      return;
    }

    token_ID = Number(tokenIdInput);
    waitingForTokenId = false;

    // Call the transfer function
    try {
      const result = await transferToken(recipientAddress, token_ID);

      // If the transfer was successful, display the result
      addTerminalContent({
        text: `${result}.`,
        format: "shog",
        useTypewriter: true,
      });
    } catch (error) {
      // Handle specific error case for USER_REFUSED_OP
      if ((error as Error).message.includes("USER_REFUSED_OP")) {
        addTerminalContent({
          text: `Transaction rejected by user. Please check your wallet and try again.`,
          format: "error",
          useTypewriter: true,
        });
      } else {
        // Handle general errors
        addTerminalContent({
          text: `Error transferring ticket: ${(error as Error).message || "An unknown error occurred."}`,
          format: "error",
          useTypewriter: true,
        });
      }
    }

    // Reset state after transfer
    recipientAddress = "";
    token_ID = null;
    waitingForTokenId = false; // Ensure the form is ready for the next input
    inputValue = "";
    await tick();
  }
</script>

<form
  bind:this={terminalForm}
  on:submit={async (e) => {
    terminalInput.disabled = true;
    if (waitingForRecipientAddress) {
      await handleRecipientAddressInput(e);
    } else if (waitingForTokenId) {
      await handleTokenIdInput(e);
    } else {
      await submitForm(e); // Normal command processing
    }
    terminalInput.disabled = false;
    terminalInput.focus();
  }}
  on:click={(e) => terminalInput.focus()}
  on:keydown={(e) => terminalInput.focus()}
  aria-label="Terminal"
  role=""
  id="terminal"
  class="font-mono overflow-y-auto h-full bg-black text-green-500 border rounded-md p-4 w-full"
  style={`border-color: ${$Dojo_Status.status === "error" ? "var(--terminal-error)" : "var(--terminal-system)"}`}
>
  <div id="scroller" class="flex items-end flex-col bottom-0 w-full">
    {#each $terminalContent as content}
      <TerminalLine {content} />
    {/each}
    <Typewriter terminalContent={$currentContentItem} />
    <!-- </ul> -->
    {#if $Dojo_Status.status === "spawning"}
      <div id="scroller" class="w-full flex flex-row gap-2">
        <span>&#x3e;</span><input
          class="bg-black text-green-700 w-full"
          type="text"
          bind:value={inputValue}
          bind:this={terminalInput}
          on:keydown={(e) => handleKeyDown(e)}
        />
        <div id="input-anchor" />
      </div>
    {/if}
  </div>
</form>

<style>
  input {
    outline: none;
  }

  #terminal {
    flex-direction: column-reverse;
    max-height: 100%;
    overflow-y: scroll;
    display: flex;
    flex-direction: column-reverse;
    min-width: 500px;
    width: 500px;
    max-width: 500px;
  }

  #scroller * {
    overflow-anchor: none;
  }

  #input-anchor {
    overflow-anchor: auto;
    height: 1px;
  }
</style>

// packages/react-client/src/components/Terminal.tsx
import { useEffect, useRef, useState } from "react";
import type { FormEvent, KeyboardEvent } from "react";
import {
	useTerminalStore,
	addTerminalContent,
	nextItem,
} from "@lib/stores/terminal.store";
import DojoStore, { useDojoStore } from "@lib/stores/dojo.store";
import Typewriter from "./Typewriter";
import TerminalLine from "./TerminalLine";
import "./Terminal.css";
import { commandHandler } from "../lib/terminalCommands/commandHandler";

export default function Terminal() {
	const [inputValue, setInputValue] = useState("");
	const [originalInputValue, setOriginalInputValue] = useState("");
	const [inputHistory, setInputHistory] = useState<string[]>([]);
	const [inputHistoryIndex, setInputHistoryIndex] = useState(0);

	const terminalFormRef = useRef<HTMLFormElement>(null);
	const terminalInputRef = useRef<HTMLInputElement>(null);

	const {
		status: { status, error },
	} = useDojoStore();
	const { terminalContent, currentContentItem } = useTerminalStore();

	useEffect(() => {
		// Focus input on mount
		if (terminalInputRef.current) {
			terminalInputRef.current.focus();
		}
		// Set timeout for connection status
		const timeout = setTimeout(() => {
			if (status !== "spawning") {
				DojoStore().setStatus({
					status: "error",
					error: "TIMEOUT",
				});
			}
		}, 5000);

		return () => clearTimeout(timeout);
	}, [status]);

	useEffect(() => {
		if (status === "spawning") return;
		if (status === "initialized") {
			addTerminalContent({
				text: [
					"\n",
					"The O'Ruggin Trail, no:23",
					"from the good folk at",
					"\n",
					"Archetypal Tech ✯",
					"\n\n\n\n\n\n\n\n\n\n",
				].join("\n"),
				format: "system",
				useTypewriter: true,
				speed: 4,
				style: JSON.stringify({ textAlign: "center" }),
			});

			addTerminalContent({
				text: 'type [command] [target], or type "help"',
				format: "input",
				useTypewriter: true,
			});

			DojoStore().setStatus({
				status: "spawning",
				error: null,
			});

			return;
		}

		if (status === "error") {
			addTerminalContent({
				text: `FATAL+ERROR: ${error}`,
				format: "error",
				useTypewriter: false,
			});

			// TODO: implement interval check to ping backend
			return;
		}
	}, [status, error]);

	// Split handleKeyDown to reduce complexity
	const handleUpArrow = (e: KeyboardEvent<HTMLInputElement>) => {
		e.preventDefault();
		if (inputHistoryIndex === 0) {
			setOriginalInputValue(inputValue);
		}
		if (inputHistoryIndex < inputHistory.length) {
			setInputHistoryIndex(inputHistoryIndex + 1);
			setInputValue(inputHistory[inputHistory.length - inputHistoryIndex - 1]);
		}
	};

	const handleDownArrow = (e: KeyboardEvent<HTMLInputElement>) => {
		e.preventDefault();
		if (inputHistoryIndex > 0) {
			setInputHistoryIndex(inputHistoryIndex - 1);
			if (inputHistoryIndex === 1) {
				setInputValue(originalInputValue);
			} else {
				setInputValue(inputHistory[inputHistory.length - inputHistoryIndex + 1]);
			}
		}
	};

	const handleKeyDown = (e: KeyboardEvent<HTMLInputElement>) => {
		switch (e.key) {
			case "ArrowUp":
				handleUpArrow(e);
				break;
			case "ArrowDown":
				handleDownArrow(e);
				break;
			case "Escape":
				e.preventDefault();
				nextItem(currentContentItem);
				break;
			default:
				break;
		}
	};

	const handleSubmit = async (e: FormEvent) => {
		e.preventDefault();

		if (terminalInputRef.current) {
			terminalInputRef.current.disabled = true;
		}
		e.preventDefault();
		const command = inputValue;
		setInputHistoryIndex(0);

		if (command === "") return;

		setInputValue("");
		setInputHistory([...inputHistory, command]);

		await commandHandler(command);

		if (terminalInputRef.current) {
			terminalInputRef.current.disabled = false;
			terminalInputRef.current.focus();
		}
	};

	const focusInput = () => {
		if (terminalInputRef.current) {
			terminalInputRef.current.focus();
		}
	};

	return (
		<div className="flex items-center justify-center w-full h-full crt">
			<form
				ref={terminalFormRef}
				onSubmit={handleSubmit}
				onClick={focusInput}
				onKeyDown={focusInput}
				aria-label="Terminal"
				role=""
				id="terminal"
				className="font-mono overflow-y-auto h-full bg-black text-green-500 border rounded-md p-4 w-full"
				style={{
					borderColor:
						status === "error" ? "var(--terminal-error)" : "var(--terminal-system)",
				}}
			>
				<div id="scroller" className="flex items-end flex-col bottom-0 w-full">
					{terminalContent.map((content, index) => (
						<TerminalLine key={index} content={content} />
					))}

					<Typewriter terminalContent={currentContentItem} />

					{status === "spawning" && (
						<div id="scroller" className="w-full flex flex-row gap-2">
							<span>&#x3e;</span>
							<input
								className="bg-transparent terminal-line system w-full"
								type="text"
								value={inputValue}
								onChange={(e) => setInputValue(e.target.value)}
								ref={terminalInputRef}
								onKeyDown={handleKeyDown}
								style={{ outline: "none" }}
							/>
							<div
								id="input-anchor"
								style={{ overflowAnchor: "auto", height: "1px" }}
							/>
						</div>
					)}
				</div>
			</form>
		</div>
	);
}
