// packages/client/src/components/Typewriter.svelte
<script lang="ts">
import { onDestroy } from "svelte";
export let text: string;
export let sentenceDelay: number = 2000;
export let minTypingDelay: number = 30;
export let maxTypingDelay: number = 200;

let displayText: string = "";
let interval: ReturnType<typeof setInterval>;

function getRandomDelay(min: number, max: number, char: string) {
	if (min < 1) return min;
	const extraDelay = /[,.!?]/.test(char) ? 20 : /[ ]/.test(char) ? 10 : 0;
	return Math.floor(Math.random() * (max - min + 1)) + min + extraDelay;
}

function typeText() {
	// Fast mode - instant display
	if (minTypingDelay === 0 && maxTypingDelay === 0 && sentenceDelay === 0) {
		displayText = text.replace(/\n/g, "<br>").replace(/\t/g, "&emsp;");
		return;
	}

	let currentIndex = 0;
	clearInterval(interval);

	interval = setInterval(() => {
		if (currentIndex >= text.length) {
			clearInterval(interval);
			return;
		}

		const char = text[currentIndex];
		displayText += char === "\n" ? "<br>" : char === "\t" ? "&emsp;" : char;
		currentIndex++;
	}, minTypingDelay);
}

$: {
	displayText = "";
	typeText();
}

onDestroy(() => {
	clearInterval(interval);
});
</script>
  
<div>{@html displayText}</div>

// packages/client/src/client/terminal/Typewriter.tsx
import { useEffect, useState } from "react";
import type { TerminalContentItem } from "@lib/stores/terminal.store";
import { nextItem, useTerminalStore } from "@lib/stores/terminal.store";
import UserStore from "@lib/stores/user.store";
import TerminalLine from "./TerminalLine";

export default function Typewriter() {
	const [displayContent, setDisplayContent] =
		useState<TerminalContentItem | null>(null);
	const minTypingDelay = 2;
	const maxTypingDelay = 9;

	const { activeTypewriterLine } = useTerminalStore();

	useEffect(() => {
		// Reset display content when activeTypewriterLine changes
		setDisplayContent(null);

		if (activeTypewriterLine === null) {
			return;
		}

		// Fast mode - instant display
		if (
			activeTypewriterLine.useTypewriter === false ||
			UserStore().typewriter_effect === false
		) {
			nextItem(activeTypewriterLine);
			return;
		}

		// Clone the content item for animation
		const newDisplayContent = { ...activeTypewriterLine, text: "" };
		setDisplayContent(newDisplayContent);

		let currentIndex = 0;
		const text = activeTypewriterLine.text;

		const interval = setInterval(
			() => {
				if (currentIndex >= text.length) {
					clearInterval(interval);
					nextItem(activeTypewriterLine);
					return;
				}

				const char = text[currentIndex];
				setDisplayContent((prev) => {
					if (!prev) return prev;
					return { ...prev, text: prev.text + char };
				});
				currentIndex++;
			},
			(activeTypewriterLine.speed || 1) *
				Math.random() *
				(maxTypingDelay - minTypingDelay) +
				minTypingDelay,
		);

		// Cleanup interval on unmount or when activeTypewriterLine changes
		return () => {
			clearInterval(interval);
		};
	}, [activeTypewriterLine]);

	if (displayContent === null) {
		return null;
	}

	return <TerminalLine content={displayContent} />;
}
