// packages/old-client/src/components/Typewriter.svelte
<script lang="ts">
  import {
    nextItem,
    type TerminalContentItem,
  } from "$lib/stores/terminal_store";
  import { onDestroy } from "svelte";
  import TerminalLine from "./TerminalLine.svelte";
  import { user_store } from "$lib/stores/user_store";
  export let terminalContent: TerminalContentItem | null;
  const minTypingDelay: number = 2;
  const maxTypingDelay: number = 9;

  let displayContent: TerminalContentItem | null = null;
  let interval: ReturnType<typeof setInterval>;

  function typeText(contentItem: TerminalContentItem | null) {
    if (contentItem === null) {
      clearInterval(interval);
      displayContent = null;
      return;
    }
    // Fast mode - instant display
    if (
      contentItem?.useTypewriter === false ||
      user_store.get().typewriter_effect === false
    ) {
      nextItem(contentItem);
      return;
    }
    const text = contentItem?.text;
    // make a clone for anim
    displayContent = Object.assign({}, contentItem);
    displayContent.text = "";

    let currentIndex = 0;
    clearInterval(interval);

    interval = setInterval(
      () => {
        if (currentIndex >= text.length) {
          clearInterval(interval);
          nextItem(contentItem);
          return;
        }

        const char = text[currentIndex];
        displayContent!.text += char;
        currentIndex++;
      },
      (terminalContent?.speed || 1) *
        Math.random() *
        (maxTypingDelay - minTypingDelay) +
        minTypingDelay
    );
  }

  $: {
    displayContent = null;
    typeText(terminalContent);
  }

  onDestroy(() => {
    clearInterval(interval);
  });
</script>

{#if displayContent !== null}
  <TerminalLine content={displayContent} />
{/if}

// packages/client/src/client/terminal/Typewriter.tsx
import { useEffect, useState } from "react";
import type { TerminalContentItem } from "@lib/stores/terminal.store";
import { nextItem, useTerminalStore } from "@lib/stores/terminal.store";
import { user_store } from "@lib/stores/user.store";
import TerminalLine from "./TerminalLine";

export default function Typewriter() {
	const [displayContent, setDisplayContent] =
		useState<TerminalContentItem | null>(null);
	const minTypingDelay = 2;
	const maxTypingDelay = 9;

	const { activeTypewriterLine } = useTerminalStore();

	useEffect(() => {
		console.warn("Typewriter", activeTypewriterLine);
		// Reset display content when activeTypewriterLine changes
		setDisplayContent(null);

		if (activeTypewriterLine === null) {
			return;
		}

		// Fast mode - instant display
		if (
			activeTypewriterLine.useTypewriter === false ||
			user_store.get().typewriter_effect === false
		) {
			nextItem(activeTypewriterLine);
			return;
		}

		// Clone the content item for animation
		const newDisplayContent = { ...activeTypewriterLine, text: "" };
		setDisplayContent(newDisplayContent);

		let currentIndex = 0;
		const text = activeTypewriterLine.text;

		const interval = setInterval(
			() => {
				if (currentIndex >= text.length) {
					clearInterval(interval);
					console.log("endlength", text.length);
					nextItem(activeTypewriterLine);
					return;
				}

				const char = text[currentIndex];
				setDisplayContent((prev) => {
					if (!prev) return prev;
					return { ...prev, text: prev.text + char };
				});
				currentIndex++;
			},
			(activeTypewriterLine.speed || 1) *
				Math.random() *
				(maxTypingDelay - minTypingDelay) +
				minTypingDelay,
		);

		// Cleanup interval on unmount or when activeTypewriterLine changes
		return () => {
			clearInterval(interval);
		};
	}, [activeTypewriterLine]);

	if (displayContent === null) {
		return null;
	}

	return <TerminalLine content={displayContent} />;
}
