// packages/client/src/editor/components/ObjectEditor.svelte
<script lang="ts">
  import { createEventDispatcher, onMount } from "svelte";
  import type { ZorgObject } from "$editor/lib/schemas";
  import {
    OBJECT_TYPE_OPTIONS,
    MATERIAL_TYPE_OPTIONS,
    DIRECTION_OPTIONS,
  } from "$editor/lib/types";
  import { actions } from "$editor/store";
  import TagInput from "./TagInput.svelte";

  export let object: ZorgObject;

  const dispatch = createEventDispatcher<{ update: ZorgObject }>();

  // Create a copy of the object for editing
  let editedObject: ZorgObject;

  // Initialize the edited object when the component mounts
  onMount(() => {
    editedObject = { ...object };
  });

  // Update the edited object when the object prop changes
  $: if (object && (!editedObject || object.objID !== editedObject.objID)) {
    editedObject = { ...object };
  }

  // Update the object when inputs change
  function handleChange() {
    dispatch("update", editedObject);
  }
</script>

<div class="space-y-4">
  <div class="form-group">
    <label for="objName" class="block text-sm font-medium text-gray-700"
      >Name</label
    >
    <input
      id="objName"
      bind:value={editedObject.name}
      on:input={handleChange}
      class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-blue-500 focus:ring-blue-500"
    />
  </div>
  <div class="form-group">
    <label for="objName" class="block text-sm font-medium text-gray-700"
      >References</label
    >
    <TagInput bind:value={editedObject.altNames} on:change={handleChange} />
    <p class="mt-1 text-xs text-gray-500">
      Alternative ways to address this object, use "," to separate multiple
      names
    </p>
  </div>

  <div class="form-group">
    <label for="objectType" class="block text-sm font-medium text-gray-700"
      >Object Type</label
    >
    <select
      id="objectType"
      bind:value={editedObject.type}
      on:change={handleChange}
      class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-blue-500 focus:ring-blue-500"
    >
      {#each OBJECT_TYPE_OPTIONS as option}
        <option value={option.value}>{option.label}</option>
      {/each}
    </select>
  </div>

  <div class="form-group">
    <label for="material" class="block text-sm font-medium text-gray-700"
      >Material</label
    >
    <select
      id="material"
      bind:value={editedObject.material}
      on:change={handleChange}
      class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-blue-500 focus:ring-blue-500"
    >
      {#each MATERIAL_TYPE_OPTIONS as option}
        <option value={option.value}>{option.label}</option>
      {/each}
    </select>
  </div>

  <div class="form-group">
    <label for="objDescription" class="block text-sm font-medium text-gray-700"
      >Object Description</label
    >
    <textarea
      id="objDescription"
      bind:value={editedObject.objDescription.text}
      on:input={handleChange}
      rows="3"
      class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-blue-500 focus:ring-blue-500"
    ></textarea>
    <div class="text-xs flex flex-col hover:text-black/40 text-black/0">
      <div class="text-nowrap">id: {editedObject.objDescription.id}</div>
      <div class="text-nowrap">owner: {editedObject.objDescription.owner}</div>
    </div>
  </div>

  <div class="form-group">
    <label for="direction" class="block text-sm font-medium text-gray-700"
      >Direction</label
    >
    <select
      id="direction"
      bind:value={editedObject.direction}
      on:change={handleChange}
      class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-blue-500 focus:ring-blue-500"
    >
      {#each DIRECTION_OPTIONS as option}
        <option value={option.value}>{option.label}</option>
      {/each}
    </select>
  </div>

  <div class="form-group">
    <label for="destination" class="block text-sm font-medium text-gray-700"
      >Destination</label
    >
    <select
      id="destination"
      bind:value={editedObject.destination}
      on:change={handleChange}
      class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-blue-500 focus:ring-blue-500"
      disabled={editedObject.direction === "None"}
    >
      <option value={null}>None</option>
      {#each actions.rooms.getAllRooms() as room}
        <option value={room.roomID}>{room.roomName}</option>
      {/each}
    </select>
    <p class="mt-1 text-xs text-gray-500">
      {editedObject.direction === "None"
        ? "Set a direction to enable destination selection."
        : "Select a room as the destination for this object."}
    </p>
  </div>

  <div class="form-group">
    <label for="objID" class="block text-sm font-medium text-gray-700"
      >Object ID</label
    >
    <input
      type="text"
      id="objID"
      bind:value={editedObject.objID}
      on:input={handleChange}
      class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-blue-500 focus:ring-blue-500"
      disabled
      readonly
    />
    <p class="mt-1 text-xs text-gray-500">
      This ID is generated automatically and should not be changed.
    </p>
  </div>
</div>

// packages/client/src/editor/components/ObjectEditor.tsx
import { useMemo, useEffect } from "react";
import type { ChangeEvent } from "react";
import type { ZorgObject, Direction } from "../lib/schemas";
import {
	OBJECT_TYPE_OPTIONS,
	MATERIAL_TYPE_OPTIONS,
	DIRECTION_OPTIONS,
} from "../lib/schemas";
import EditorStore, { useEditorStore } from "../store";
import { EditorList } from "./EditorList";
import {
	Header,
	DeleteButton,
	Select,
	Textarea,
	TextDef,
	TagInput,
	ItemId,
	Input,
} from "./FormComponents";

export const ObjectEditor = ({
	currentObjectIndex,
	setCurrentObjectIndex,
}: {
	currentObjectIndex: number;
	setCurrentObjectIndex: React.Dispatch<React.SetStateAction<number>>;
}) => {
	const { currentLevel, currentRoomIndex } = useEditorStore();

	// Get the current room from global state
	const currentRoom = useMemo(() => {
		return currentLevel.rooms[currentRoomIndex];
	}, [currentLevel, currentRoomIndex]);

	// Get the current object based on selected index
	const currentObject = useMemo(() => {
		return currentRoom?.objects?.[currentObjectIndex] || null;
	}, [currentRoom, currentObjectIndex]);

	// Handle out-of-bounds index when objects change
	useEffect(() => {
		if (
			currentRoom?.objects?.length > 0 &&
			currentObjectIndex >= currentRoom.objects.length
		) {
			setCurrentObjectIndex(0);
		}
	}, [currentRoom, currentObjectIndex, setCurrentObjectIndex]);

	// Select a different object
	const selectObjectIndex = (index: number) => {
		setCurrentObjectIndex(index);
	};

	// Add a new object to the room
	const handleAddObject = () => {
		EditorStore().objects.add();
		// Select the new object on next render
		const newIndex = currentRoom.objects.length;
		setTimeout(() => {
			setCurrentObjectIndex(newIndex);
		}, 0);
	};

	// Delete the current object
	const handleDeleteObject = () => {
		if (!currentObject) return;

		EditorStore().objects.delete(currentObjectIndex);
		// Adjust the current object index if needed
		if (currentObjectIndex >= currentRoom.objects.length - 1) {
			setCurrentObjectIndex(Math.max(0, currentRoom.objects.length - 2));
		}
	};

	// Update text fields
	const handleTextChange = (id: string, value: string) => {
		if (!currentObject) return;

		const updatedObject: ZorgObject = { ...currentObject };

		if (id === "objName") {
			updatedObject.name = value;
		} else if (id === "objDescription") {
			updatedObject.objDescription = {
				...updatedObject.objDescription,
				text: value,
			};
		}

		EditorStore().objects.update(currentObjectIndex, updatedObject);
	};

	// Update select dropdowns - simplified to reduce complexity
	const handleSelectChange = (id: string, value: string) => {
		if (!currentObject) return;

		const updatedObject: ZorgObject = { ...currentObject };

		switch (id) {
			case "objectType":
				updatedObject.type = value;
				break;
			case "material":
				updatedObject.material = value;
				break;
			case "direction":
				updatedObject.direction = value === "None" ? null : (value as Direction);
				if (value === "None") {
					updatedObject.destination = null;
				}
				break;
			case "destination":
				updatedObject.destination = value === "null" ? null : value;
				break;
		}

		EditorStore().objects.update(currentObjectIndex, updatedObject);
	};

	// Handle input changes - delegate to appropriate handlers
	const handleInputChange = (
		e: ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>,
	) => {
		const { id, value } = e.target;

		if (id === "objName" || id === "objDescription") {
			handleTextChange(id, value);
		} else {
			handleSelectChange(id, value);
		}
	};

	// Handle tag input changes - properly implemented
	const handleTagChange = (tags: string[]) => {
		if (!currentObject) return;

		const updatedObject: ZorgObject = {
			...currentObject,
			altNames: tags,
		};

		EditorStore().objects.update(currentObjectIndex, updatedObject);
	};

	return (
		<div className="flex flex-col gap-4">
			<EditorList
				list={currentRoom?.objects || []}
				selectionFn={selectObjectIndex}
				selectedIndex={currentObjectIndex}
				addObjectFn={handleAddObject}
				emptyText="Create new object"
			/>

			{!currentObject ? (
				<div className="flex flex-col space-y-4">
					<p>No objects.</p>
				</div>
			) : (
				<div className="editor-inspector">
					<Header title="Object">
						<DeleteButton onClick={handleDeleteObject} />
					</Header>
					<Input
						id="objName"
						value={currentObject.name}
						onChange={handleInputChange}
					/>
					<TagInput
						id="altNames"
						value={currentObject.altNames.join(", ")}
						onChange={handleTagChange}
						description={`Alternative ways to address this object, use \",\" to separate multiple names`}
					/>
					<Select
						id="objectType"
						value={currentObject.type}
						onChange={handleInputChange}
						options={OBJECT_TYPE_OPTIONS}
					/>
					<Select
						id="material"
						value={currentObject.material}
						onChange={handleInputChange}
						options={MATERIAL_TYPE_OPTIONS}
					/>
					<Textarea
						id="objDescription"
						value={currentObject.objDescription.text}
						onChange={handleInputChange}
						rows={3}
					>
						<TextDef
							id={currentObject.objDescription.id}
							owner={currentObject.objDescription.owner}
						/>
					</Textarea>
					<Select
						id="direction"
						value={currentObject.direction || "None"}
						onChange={handleInputChange}
						options={DIRECTION_OPTIONS}
					/>
					<Select
						id="destination"
						value={currentObject.destination || "null"}
						onChange={handleInputChange}
						options={EditorStore()
							.rooms.getAllRooms()
							.map((room) => ({
								value: room.roomID,
								label: room.roomName,
							}))}
					/>
					<ItemId id={currentObject.objID} />
				</div>
			)}
		</div>
	);
};

export default ObjectEditor;
