// packages/old-client/src/editor/components/TagInput.svelte
<script lang="ts">
  import { createEventDispatcher } from "svelte";
  export let value: string[] = []; // tag list
  let input = ""; // input value

  const dispatch = createEventDispatcher();
  // pressed checks keyboard event for comma or Enter key.
  // If found, adds 'value' in the tag list.
  // REM: On the 'blur' event, if we exit the field with
  //      someting inside, consider it as a tag.
  function pressed(event: FocusEvent | KeyboardEvent) {
    // Check if conditions are met to do something.
    // If not, exit as early as possible.
    if (
      event.type !== "blur" &&
      (event as KeyboardEvent).key !== "," &&
      (event as KeyboardEvent).key !== "Enter"
    )
      return;

    // Clean the remaining comma in input.
    input = input.replace(",", "").trim();
    // remove empty
    if (input === "" || input.match(/^\s*$/) || value.includes(input)) {
      input = "";
      return;
    }

    value = [...value, input];
    input = "";
    dispatch("change", {
      value,
    });
  }

  // Del removes item from Taglist
  function del(idx: number) {
    value.splice(idx, 1);
    // biome-ignore lint/correctness/noSelfAssign: <@dev required to force parent to update>
    value = value;
    dispatch("change", {
      value,
    });
  }
</script>

<input
  list="tag_suggestion"
  on:blur={pressed}
  on:keyup={pressed}
  bind:value={input}
  class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-blue-500 focus:ring-blue-500"
/>
<div>
  {#each value as t, i}
    <span class="tag">
      {t} <a href="#del" class="tag-handler" on:click={() => del(i)}>⨉</a>
    </span>
  {/each}
</div>

<style lang="postcss">
  @reference "tailwindcss";

  .tag-handler {
    @apply ml-2 text-black;
  }

  .tag a {
    @apply decoration-0;
  }
</style>

// packages/client/src/editor/components/TagInput.tsx
import { cn } from "@/lib/utils";
import { useState } from "react";
import type { KeyboardEvent, FocusEvent } from "react";

interface TagInputProps {
	value: string[];
	onChange: (tags: string[]) => void;
	className?: string;
}

export const TagInput = ({ value, onChange, className }: TagInputProps) => {
	const [input, setInput] = useState("");

	// Handles keyboard events and blur to add new tags
	const handleInputEvent = (
		event: FocusEvent<HTMLInputElement> | KeyboardEvent<HTMLInputElement>,
	) => {
		// Check if conditions are met to add a tag
		if (
			event.type !== "blur" &&
			(event as KeyboardEvent<HTMLInputElement>).key !== " " &&
			(event as KeyboardEvent<HTMLInputElement>).key !== "," &&
			(event as KeyboardEvent<HTMLInputElement>).key !== "Enter"
		) {
			return;
		}

		// Clean the remaining comma in input
		const cleanedInput = input.replace(",", "").trim();

		// Don't add if empty or already exists
		if (
			cleanedInput === "" ||
			cleanedInput.match(/^\s*$/) ||
			value.includes(cleanedInput)
		) {
			setInput("");
			return;
		}

		// Add the new tag
		const newTags = [...value, cleanedInput];
		onChange(newTags);
		setInput("");
	};

	// Removes a tag at the specified index
	const handleRemoveTag = (idx: number) => {
		const newTags = [...value];
		newTags.splice(idx, 1);
		onChange(newTags);
	};

	return (
		<>
			<input
				list="tag_suggestion"
				onBlur={handleInputEvent}
				onKeyUp={handleInputEvent}
				value={input}
				onChange={(e) => setInput(e.target.value)}
				className={cn(
					"mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-blue-500 focus:ring-blue-500",
				)}
			/>
			<div className="flex flex-wrap mt-2">
				{value.map((tag, index) => {
					if (tag === "") return null;
					return (
						<span
							key={index}
							className="tag inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2"
						>
							{tag}{" "}
							<a
								href="#del"
								className="tag-handler ml-2 text-black no-underline"
								onClick={(e) => {
									e.preventDefault();
									handleRemoveTag(index);
								}}
							>
								⨉
							</a>
						</span>
					);
				})}
			</div>
		</>
	);
};
