// packages/client/src/client/terminal/TerminalLine.tsx
import { cn } from "../../lib/utils/utils";
import type { TerminalContentItem } from "@lib/stores/terminal.store";
import "./Terminal.css";

interface TerminalLineProps {
	content: TerminalContentItem | null;
}

export default function TerminalLine({ content }: TerminalLineProps) {
	if (content === null) {
		return null;
	}

	// Parse the text with newlines and tabs for safe rendering
	const contentText = content.text
		.replace(/\n/g, "<br>")
		.replace(/\t/g, "&emsp;");

	const { format } = content;

	return (
		<div
			className={cn(
				`terminal-line w-full`,
				format !== "input" && "textFreak",
				format === "shog" && "shog",
				format === "out" && "out",
				format === "system" && "system",
				format === "error" && "error",
				format === "hash" && "hash",
				format === "input" && "input",
			)}
			style={content.style || {}}
			// biome-ignore lint/security/noDangerouslySetInnerHtml: <Using dangerouslySetInnerHTML is necessary here for the newline formatting>
			dangerouslySetInnerHTML={{
				__html: contentText,
			}}
		/>
	);
}

// packages/old-client/src/components/TerminalLine.svelte
<script lang="ts">
  import type { TerminalContentItem } from "$lib/stores/terminal_store";

  export let content: TerminalContentItem | null;
</script>

{#if content !== null}
  <div
    class="terminal-line w-full"
    class:shog={content.format === "shog"}
    class:out={content.format === "out"}
    class:textFreak={content.format === "out" ||
      content.format === "system" ||
      content.format === "hash" ||
      content.format === "shog"}
    class:input={content.format === "input"}
    class:hash={content.format === "hash"}
    class:error={content.format === "error"}
    class:system={content.format === "system"}
    style={content.style}
  >
    {@html content.text.replace(/\n/g, "<br>").replace(/\t/g, "&emsp;")}
  </div>
{/if}

<style>
  .terminal-line {
    font-size: 1.02em;
  }
  .terminal-line.hash {
    color: var(--terminal-hash);
    font-weight: bold;
  }
  .terminal-line.out {
    color: var(--terminal-out);
  }
  .terminal-line.shog {
    color: var(--terminal-shog);
  }
  .terminal-line.input {
    color: var(--terminal-input);
  }
  .terminal-line.system {
    color: var(--terminal-system);
  }
  .terminal-line.error {
    color: var(--terminal-error);
  }
</style>
